name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update docker image
      run: apt-get -y update && apt-get -y upgrade
      
    - name: Install dependencies
      run: sudo apt install -y nasm libsdl2-dev

    - name: Compile
      run: make
